[tool.towncrier]
directory = "docs/migrations"
filename = "MIGRATIONS.md"
template = ".github/migration-notes.md.jinja"
title_format = ""
wrap = false
all_bullets = false

[[tool.towncrier.type]]
directory = "breaking"
name = "Breaking changes and migration"
showcontent = true
